### ISSUE TITLE
Different amplicons size from BioMocks sequenced on different platforms (Illumina vs PGM).

### ISSUE THREAD

**Issue by bsmoda** [nextgenusfs/amptk#74]
Hello @nextgenusfs , how are you?

I'm trying to replicate your results from the AMPTk paper with the BioMocks sequences.
I've performed separated analysis from Illumina vs PGM data, I've used the same primers you mentioned in the paper (fITS7 and ITS4), and I think the only difference of the analysis was the clustering method. I've used trim-length = 400 in the demux step, unoise3 in clustering step (because the dada2 method was taking too long to complete), filtering step following the amptk tutorial and taxonomy using ITS2 db.
I've taken the table below as expected results. First I've checked the Illumina results and it were in accordance with your results (length, GC%, and total counts), but when I checked the PGM results it was a lot different from the table. The amplicon length for all OTU was higher than the expected, the GC% was somewhat similar for some OTUs, and the counts were similar for some but really different for other OTUs. Is there something I'm doing it wrong?
Thank you for your help :)

![fig-4-1x](https://user-images.githubusercontent.com/35775683/77709705-b0d39080-6faa-11ea-85aa-b1aa63d9af29.jpg)

**Comment by nextgenusfs** [comment]
To get "identical" results you'd have to use the same version of AMPtk I used in the paper (v1.0.1), see analysis workflow here to generate these data. https://osf.io/67bc2/.  

Specifically from the juptyer notebook in the OSF folder, note length set to 300.  Length will have a large effect on the Ion PGM data due to the reads being single ended and lose quality as they get to the 3' end of the molecule.  Since we use expected errors trimming, this will result in reads being thrown out at the filtering stage if you set the length to something longer, which would then of course effect the clusters you obtain, etc. 

However, this figure you are referring to was generated by mapping dumuxed reads to the mock community (ie reference based). The GC and length are based off of the actual ITS2 sequences that were sequenced with Sanger, not the results from any of the NGS platforms. So this was not de novo clustered, ie using UPARSE/UNOISE/etc. The reason for this is that here we started with a defined community, these results indicate that PCR on mixed community is biasing the abundance metrics -- ie the crux of the argument in our paper, that these abundances cannot be used a proxy for biological abundance. 

```
#amptk ion demux with 0 mismatches
amptk ion -i mock3.ion.fastq.gz -m mapping_files/ion3.mapping_file.txt --min_len 100 -o ion3 -l 300

#Want to map the BioMock runs to the BioMock community to look at read abundance
#pull out samples from each demuxed BioMock run
#then create OTU table, reorder results and then draw heatmap
amptk select -i ion3.demux.fq.gz -l m3-stds m3-mock3-16000 m3-mock3-32000a m3-mock3-32000b -o ion3.biomock.fq.gz
amptk select -i m4a.demux.fq.gz -l m4A-stds m4A-mock3-16000 m4A-mock3-32000a m4A-mock3-32000b -o m4a.biomock.fq.gz

#convert to fasta
vsearch --fastq_filter ion3.biomock.fq.gz --fastaout ion3.biomock.fa
vsearch --fastq_filter m4a.biomock.fq.gz --fastaout m4a.biomock.fa

#map to biomock OTUs
vsearch --usearch_global ion3.biomock.fa --otutabout ion3.biomock.otu_table.txt --id 0.97 \
    --db $HOME/amptk/DB/amptk_mock2.fa
vsearch --usearch_global m4a.biomock.fa --otutabout m4a.biomock.otu_table.txt --id 0.97 \
    --db $HOME/amptk/DB/amptk_mock2.fa


#draw heatmap
amptk heatmap -i ion3.biomock.otu_table.txt --color YlOrBr -m heatmap --annotate -o ion3.biomock.pdf
amptk heatmap -i m4a.biomock.otu_table.txt --color YlOrBr -m heatmap --annotate -o m4a.biomock.pdf
```
